name: store
description: "Store ( Products Catalog ) project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  dio: ^5.8.0+1
  file_picker: ^9.0.2
  easy_localization: ^3.0.7+1
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.17
  delightful_toast: ^1.1.0
  equatable: ^2.0.7
  shimmer: ^3.0.0
  gradient_borders: ^1.0.1
  device_info_plus: ^11.3.3
  internet_connection_checker_plus: ^2.7.1
  package_info_plus: ^8.3.0
  intl: ^0.19.0
  geocoding: ^3.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/json/lang/en.json
    - assets/json/lang/ar.json
    - assets/images/home/